version: "3.4"

services:
  bthfrontend:
    image: bthfrontend:v1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    expose:
      - 3000
