export const SLOGANS = [
  'Your heart is filled with love.',
  'Your contribution. Many solutions',
  'Your contribution can help achieve a solution',
  'Your change can make a change.',
  'Your act is appreciating',
  'You think, you care, you give.',
  'You may feel like a drop in the bucket. But every drop counts!',
  'You have, you can give',
  'You have the power to bring happiness.',
  'You have the power to change the world.',
  'You giving means you are loving.',
  'You can make a Difference, so why don’t you?',
  'You can help.',
  'A safe place where healing begins.',
  'A small charity has a big impact',
  'Actions speak louder than words! Give today.',
  'An effort made for the happiness of others lifes us above ourselves.  ',
];
export const LIMIT_FILE = 10;
